In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
name='randolph'
name

'randolph'

In [6]:
name[:-5]

'ran'

In [10]:
data = pd.read_excel('climate_change.xls')
data.head()

Country code Country name     Series code  \
0          ABW        Aruba  AG.LND.EL5M.ZS   
1          ADO      Andorra  AG.LND.EL5M.ZS   
2          AFG  Afghanistan  AG.LND.EL5M.ZS   
3          AGO       Angola  AG.LND.EL5M.ZS   
4          ALB      Albania  AG.LND.EL5M.ZS   

                           Series name SCALE Decimals      1990 1991 1992  \
0  Land area below 5m (% of land area)     0        1  29.57481   ..   ..   
1  Land area below 5m (% of land area)     0        1         0   ..   ..   
2  Land area below 5m (% of land area)     0        1         0   ..   ..   
3  Land area below 5m (% of land area)     0        1  0.208235   ..   ..   
4  Land area below 5m (% of land area)     0        1  4.967875   ..   ..   

  1993  ... 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011  
0   ..  ...   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..  
1   ..  ...   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..  
2   ..  ...   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..  
3   ..  ...   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..  
4   ..  ...   ..   ..   ..   ..   ..   ..   ..   ..   ..   ..  

[5 rows x 28 columns]

In [11]:
data.dtypes

Country code    object
Country name    object
Series code     object
Series name     object
SCALE           object
Decimals        object
1990            object
1991            object
1992            object
1993            object
1994            object
1995            object
1996            object
1997            object
1998            object
1999            object
2000            object
2001            object
2002            object
2003            object
2004            object
2005            object
2006            object
2007            object
2008            object
2009            object
2010            object
2011            object
dtype: object

In [17]:
data['Country code'].isnull().value_counts()

False    13512
Name: Country code, dtype: int64

In [24]:
data['Country name'] = data['Country name'].astype(str)

In [26]:
data = data.loc[data['Country name'] == 'Panama',:]
data.head()

Country code Country name           Series code  \
164           PAN       Panama        AG.LND.EL5M.ZS   
397           PAN       Panama     AG.LND.IRIG.AG.ZS   
630           PAN       Panama        AG.YLD.CREL.KG   
863           PAN       Panama  BX.KLT.DINV.WD.GD.ZS   
1096          PAN       Panama        EG.ELC.ACCS.ZS   

                                            Series name SCALE Decimals  \
164                 Land area below 5m (% of land area)     0        1   
397   Agricultural land under irrigation (% of total...     0        1   
630                       Cereal yield (kg per hectare)     0        0   
863   Foreign direct investment, net inflows (% of GDP)     0        1   
1096      Access to electricity (% of total population)     0        1   

          1990      1991      1992      1993  ...      2002      2003  \
164   3.705232        ..        ..        ..  ...        ..        ..   
397         ..        ..        ..        ..  ...        ..        ..   
630     1866.6    1882.9    1835.8    1898.7  ...    1980.3    1986.7   
863   2.550252  1.857145  2.175746  2.338439  ...  0.803429  6.320941   
1096        ..        ..        ..        ..  ...        ..        ..   

          2004      2005       2006      2007      2008      2009      2010  \
164         ..        ..         ..        ..        ..        ..        ..   
397         ..        ..         ..        ..        ..        ..        ..   
630     1694.8    1871.9     2146.1    2191.8      2735    2019.2        ..   
863   7.187238  5.933513  14.921515  8.974942  9.548031  7.362096  8.822837   
1096        ..        ..         ..        ..        ..      88.1        ..   

     2011  
164    ..  
397    ..  
630    ..  
863    ..  
1096   ..  

[5 rows x 28 columns]

In [27]:
data['Series name'].value_counts()

Land area below 5m (% of land area)                                 1
GNI per capita (Atlas $)                                            1
Population below 5m (% of total)                                    1
Population in urban agglomerations >1million (%)                    1
Annual freshwater withdrawals (% of internal resources)             1
Nationally terrestrial protected areas (% of total land area)       1
Ease of doing business (ranking 1-183; 1=best)                      1
Invest. in energy w/ private participation ($)                      1
Invest. in telecoms w/ private participation ($)                    1
Invest. in transport w/ private participation ($)                   1
Invest. in water/sanit. w/ private participation ($)                1
Public sector mgmt & institutions avg. (1-6 scale; 6=best)          1
Paved roads (% of total roads)                                      1
GDP ($)                                                             1
Ratio of girls to bo

In [28]:
df = pd.DataFrame()

In [2]:
#data.melt(id_vars=["GDP ($)", "Population", "Urban population", "Nationally terrestrial protected areas (% of total land area)"],
#    var_name="Date",
#    value_name="Value")


In [30]:
df = data.loc[data['Series name'] == 'GDP ($)', :]
df.head()

Country code Country name     Series code Series name SCALE Decimals  \
9950          PAN       Panama  NY.GDP.MKTP.CD     GDP ($)     0        0   

            1990        1991        1992        1993  ...         2002  \
9950  5313200000  5842300000  6641400000  7252700000  ...  12272400000   

             2003         2004         2005         2006         2007  \
9950  12933200000  14179300000  15464700000  17137000000  19794000000   

             2008         2009         2010 2011  
9950  23001600000  24080100000  26777100000   ..  

[1 rows x 28 columns]

In [33]:
#df.rename(columns={"Series name": "GDP ($)"})
df = df.apply(lambda x: 1 if x['Series name'] == 'GDP ($)' else 0, axis= 1)

Country code Country name     Series code Series name SCALE Decimals  \
9950          PAN       Panama  NY.GDP.MKTP.CD     GDP ($)     0        0   

            1990        1991        1992        1993  ...         2002  \
9950  5313200000  5842300000  6641400000  7252700000  ...  12272400000   

             2003         2004         2005         2006         2007  \
9950  12933200000  14179300000  15464700000  17137000000  19794000000   

             2008         2009         2010 2011  
9950  23001600000  24080100000  26777100000   ..  

[1 rows x 28 columns]

In [14]:
dataset = pd.read_csv("Data.csv")
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [80]:
X = dataset.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [81]:
Y = dataset.iloc[:, -1]
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [82]:
Y.dtypes

dtype('O')

In [83]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [84]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [85]:
from sklearn.compose import ColumnTransformer
#OneHotEncoder is used for several categorical data
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))


In [86]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [87]:
#LabelEncoder is used for two categorical data which can be directly encoded to 0 and 1
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [88]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [89]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=1)

In [90]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [91]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [92]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [93]:
print(Y_test)

[0 1]


In [94]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [95]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [96]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
