# Support Vector Regression (SVR)

## Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
dataset = pd.read_csv('Position_Salaries.csv')
dataset.head()

Position  Level  Salary
0   Business Analyst      1   45000
1  Junior Consultant      2   50000
2  Senior Consultant      3   60000
3            Manager      4   80000
4    Country Manager      5  110000

In [4]:
x =  dataset.iloc[:,1:-1].values
x[:5]

array([[1],
       [2],
       [3],
       [4],
       [5]], dtype=int64)

In [5]:
y = dataset.iloc[:,-1].values
y[:5]

array([ 45000,  50000,  60000,  80000, 110000], dtype=int64)

In [6]:
y = y.reshape(len(y),1)
y[:5]

array([[ 45000],
       [ 50000],
       [ 60000],
       [ 80000],
       [110000]], dtype=int64)

## Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x = sc_x.fit_transform(x)
y = sc_y.fit_transform(y)

In [17]:
x[:5]

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766]])

In [18]:
y[:5]

array([[-0.72004253],
       [-0.70243757],
       [-0.66722767],
       [-0.59680786],
       [-0.49117815]])

## Training the SVR model on the whole dataset

In [26]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(x,y)

SVR()

## Predicting a new result

In [27]:
regressor.predict(sc_x.transform([[6.5]]))

array([0.01150915])

In [29]:
sc_y.inverse_transform([regressor.predict(sc_x.transform([[6.5]]))])

array([[0.01150915]])

## Visualising the SVR results

## Visualising the SVR results (for higher resolution and smoother curve)